[build]
builder = "NIXPACKS"
buildCommand = """
pip install --upgrade pip &&
echo "📦 Installing core packages..." &&
pip install fastapi uvicorn pydantic sqlalchemy alembic psycopg2-binary &&
echo "📦 Installing auth & networking..." &&
pip install python-jose python-multipart bcrypt aiohttp requests httpx &&
echo "📦 Installing AI services..." &&
pip install anthropic 'openai>=1.10.0,<2.0.0' boto3 python-dotenv redis &&
echo "📦 Installing data processing..." &&
pip install 'numpy<2.0.0,>=1.26.2' 'pandas>=2.0.0' 'pinecone>=3.0.0' &&
echo "📦 Installing ML packages (this will take a few minutes)..." &&
pip install --index-url https://download.pytorch.org/whl/cpu torch==2.1.0 &&
pip install torch-geometric scikit-learn sentence-transformers matplotlib scipy 'huggingface_hub<0.19.0' 'langchain>=0.1.17' 'langchain-openai>=0.1.6' &&
echo "✅ All packages installed successfully!"
"""

[deploy] 
startCommand = "python fix_railway_sequences.py && uvicorn main_deploy:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"

[build.env]
# CPU-optimized torch for faster downloads  
PIP_INDEX_URL = "https://download.pytorch.org/whl/cpu"
PIP_EXTRA_INDEX_URL = "https://pypi.org/simple/"

[build.cache]
enabled = true
